server:
  port: 8081

web:
  api:
    pagination:
      default-page: 0
      default-page-size: 20

spring:
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  main:
    web-application-type: reactive

application:
  use-cases:
    binding: users
  security:
    authentication:
      methods:
        active: jwt
        basic:
          realm-name: default
        jwt:
          issuer: Task Management Application
          secret-key:
          expiry-time-sec: 300
      admin:
        id: admin
        secret: admin
        first-name: Ruslan
        last-name: Nigmatullin

