server:
  port: 8081

spring:
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

management:
  endpoint:
    beans:
      enabled: true

    health:
      enabled: true

    metrics:
      enabled: true

  main:
    web-application-type: reactive