server:
  port: 8081

web:
  api:
    pagination:
      default-page: 0
      default-page-size: 20

spring:
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

