spring:
  application:
    name: ToDos App Dev

  datasource:
    driver-class-name: org.h2.Driver
    password: 123456
    username: sa
    name: ToDoDataSource
    url: jdbc:h2:mem:todos

  jpa:
    hibernate:
      ddl-auto: update
    database: h2

  h2:
    console:
      enabled: true
      path: /h2-dev