spring:
  application:
    name: ToDos App

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yml

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database: postgresql

  datasource:
    url: jdbc:postgresql://localhost/todos
    name: ToDoDataSource
    username: todo_user
    password: todo_user
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: PooledToDoDataSource
      minimum-idle: 5
      maximum-pool-size: 12
