spring:
  application:
    name: ToDos App

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql

  datasource:
    url: jdbc:postgresql://srv-pg2/todos
    name: ToDoDataSource
    username: u_59968
    password: 123456
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: PooledToDoDataSource
      minimum-idle: 5
      maximum-pool-size: 12
